import { describe, it, expect } from 'vitest';
import { generateTypedFunctions } from '../generator.js';
import type { ParsedTranslations } from '../parser.js';

describe('generateTypedFunctions', () => {
  it('should generate code for simple translations', () => {
    const translations: ParsedTranslations = {
      hello: 'Hello',
      goodbye: 'Goodbye',
    };

    const code = generateTypedFunctions(translations, 'en');

    expect(code).toContain('export function hello(): string');
    expect(code).toContain('export function goodbye(): string');
    expect(code).toContain("return messages['hello']");
    expect(code).toContain("return messages['goodbye']");
  });

  it('should generate code with parameters', () => {
    const translations: ParsedTranslations = {
      welcome: 'Welcome, {name}!',
    };

    const code = generateTypedFunctions(translations, 'en');

    expect(code).toContain('export function welcome(params:');
    expect(code).toContain('name:');
  });

  it('should include setLocale and getLocale functions', () => {
    const translations: ParsedTranslations = {};

    const code = generateTypedFunctions(translations, 'en');

    expect(code).toContain('export function setLocale(locale: Locale): void');
    expect(code).toContain('export function getLocale(): Locale');
  });

  it('should generate the m object with all keys', () => {
    const translations: ParsedTranslations = {
      key1: 'Value 1',
      key2: 'Value 2',
    };

    const code = generateTypedFunctions(translations, 'en');

    expect(code).toContain('export const m = {');
    expect(code).toContain('key1,');
    expect(code).toContain('key2,');
  });

  it('should include auto-generated comment', () => {
    const translations: ParsedTranslations = {};

    const code = generateTypedFunctions(translations, 'en');

    expect(code).toContain('Auto-generated by @typeglot/compiler');
    expect(code).toContain('Do not edit manually');
  });

  it('should escape backticks in default values', () => {
    const translations: ParsedTranslations = {
      code: 'Use `code` here',
    };

    const code = generateTypedFunctions(translations, 'en');

    expect(code).toContain('\\`code\\`');
  });
});
