/**
 * Example file demonstrating TypeGlot VS Code extension features.
 *
 * Open this file with the TypeGlot extension active to see:
 * - Inline translation previews (ghost text)
 * - Code actions for missing keys
 * - JSDoc context extraction
 */

// Import the generated translation messages
// In a real project, this would be auto-generated by `typeglot build`
declare const m: {
  welcome(): string;
  hello(params: { name: string }): string;
  items_count(params: { count: number }): string;
  checkout_now(): string;
  save_settings(): string;
  profile_updated(): string;
  // These keys are "missing" to demonstrate the extension features:
  new_feature(): string;
  payment_failed(): string;
};

// ============================================================================
// EXAMPLE 1: Basic translation usage
// ============================================================================

// The extension will show ghost text: → "Welcome to TypeGlot!"
const welcomeMessage = m.welcome();

// With parameters: → "Hello, {name}!"
function greetUser(userName: string) {
  return m.hello({ name: userName });
}

// ============================================================================
// EXAMPLE 2: Pluralization
// ============================================================================

// The extension shows the ICU plural pattern
function displayCartCount(count: number) {
  return m.items_count({ count });
}

// ============================================================================
// EXAMPLE 3: JSDoc context for AI translations
// ============================================================================

/**
 * @desc Button displayed when user finalizes their checkout.
 * Should convey urgency and action.
 */
const checkoutButton = m.checkout_now();

/**
 * @desc Success message shown after the user saves their profile settings.
 * @context Displayed in a toast notification at the bottom of the screen.
 */
function saveUserProfile() {
  // ... save logic ...
  return m.profile_updated();
}

// ============================================================================
// EXAMPLE 4: Missing translations (triggers Code Actions)
// ============================================================================

/**
 * @desc Announcement banner for a new product feature.
 * @context Homepage hero section, should be exciting and engaging.
 */
// This key doesn't exist in en.json - hover to see the warning!
// Press Cmd+. (or click the lightbulb) to create it with AI
const newFeature = m.new_feature();

/**
 * @desc Error message when payment processing fails.
 * @context Modal dialog shown after payment attempt fails.
 * Should be apologetic and offer next steps.
 */
// Another missing key - the AI will use this JSDoc for context
const paymentError = m.payment_failed();

// ============================================================================
// EXAMPLE 5: Hardcoded strings to extract
// ============================================================================

// Select this string and use "TypeGlot: Extract String to Translation"
const hardcodedMessage = 'This is a hardcoded string that should be translated';

// The extension will offer to extract it to a translation key

// ============================================================================
// EXAMPLE 6: Different patterns the extension recognizes
// ============================================================================

// Pattern 1: m.key_name()
const pattern1 = m.welcome();

// Pattern 2: m.key_name (without parentheses)
const pattern2 = m.welcome;

// Pattern 3: t('key_name') - common i18n pattern
declare function t(key: string): string;
const pattern3 = t('welcome');

export {
  welcomeMessage,
  greetUser,
  displayCartCount,
  checkoutButton,
  saveUserProfile,
  newFeature,
  paymentError,
  hardcodedMessage,
};
